module.exports=[
  {
      city: 'Patenga, Chittagong',
      spotName: 'Patenga Beach',
      latitude: '22.2782',
      longitude: '91.8141',
      type: 'beach',
      rank: 1, 
  },
  {
      city: 'Khulshi, Chittagong',
      spotName: "Foy's Lake",
      latitude: '22.3794',
      longitude: '91.8223',
      type: 'lake',
      rank: 2,
  },
  {
      city: 'Kotwali, Chittagong',
      spotName: 'Karnaphuli River',
      latitude: '22.3475',
      longitude: '91.8123',
      type: 'river',
      rank: 3,
  },
  {
      city: 'Ruma, Chittagong',
      spotName: 'Boga Lake',
      latitude: '21.8883',
      longitude: '92.2836',
      type: 'lake',
      rank: 4,
  },
  {
      city: 'Cox\'s Bazar Sadar, Chittagong',
      spotName: "Cox's Bazar Beach",
      latitude: '21.4272',
      longitude: '91.9726',
      type: 'beach',
      rank: 5,
  },
  {
      city: 'Baghaichhari, Chittagong',
      spotName: 'Sajek Valley',
      latitude: '23.3814',
      longitude: '92.2937',
      type: 'valley',
      rank: 6,
  },
  {
      city: 'Maheshkhali, Chittagong',
      spotName: 'Maheshkhali Island',
      latitude: '21.8469',
      longitude: '91.9655',
      type: 'island',
      rank: 7,
  },
  {
      city: 'Ukhiya, Chittagong',
      spotName: 'Inani Beach',
      latitude: '21.4355',
      longitude: '91.9707',
      type: 'beach',
      rank: 8,
  },
  {
      city: 'Patenga, Chittagong',
      spotName: 'Patenga Sea World',
      latitude: '22.2778',
      longitude: '91.8145',
      type: 'sea world',
      rank: 9,
  },
  {
      city: 'Ramu, Chittagong',
      spotName: 'Himchari National Park',
      latitude: '21.4025',
      longitude: '91.9593',
      type: 'national park',
      rank: 10,
  },
  {
      city: 'Bakalia, Chittagong',
      spotName: 'Shah Amanat Bridge',
      latitude: '22.3465',
      longitude: '91.7972',
      type: 'bridge',
      rank: 11,
  },
  {
      city: 'Agrabad, Chittagong',
      spotName: 'Ethnological Museum of Chittagong',
      latitude: '22.3481',
      longitude: '91.8318',
      type: 'museum',
      rank: 12,
  },
  {
      city: 'Dampara, Chittagong',
      spotName: 'Chittagong War Cemetery',
      latitude: '22.3365',
      longitude: '91.8424',
      type: 'cemetery',
      rank: 13,
  },
  {
      city: 'Sitakunda, Chittagong',
      spotName: 'Sitakunda Eco Park',
      latitude: '22.3613',
      longitude: '91.7803',
      type: 'eco park',
      rank: 14,
  },
  {
      city: 'Bhatiary, Chittagong',
      spotName: 'Vatiary Lake',
      latitude: '22.4563',
      longitude: '91.7942',
      type: 'lake',
      rank: 15,
  },
  {
      city: 'Bhatiary, Chittagong',
      spotName: 'Bhatiari Lake',
      latitude: '22.4451',
      longitude: '91.7985',
      type: 'lake',
      rank: 16,
  },
  {
      city: 'Patenga, Chittagong',
      spotName: 'Patenga Mini World',
      latitude: '22.2782',
      longitude: '91.8141',
      type: 'mini world',
      rank: 17,
  },
  {
      city: 'Khulshi, Chittagong',
      spotName: 'Chittagong Zoo',
      latitude: '22.3409',
      longitude: '91.8252',
      type: 'zoo',
      rank: 18,
  },
  {
      city: 'Sitakunda, Chittagong',
      spotName: 'Chandranath Hill',
      latitude: '22.5438',
      longitude: '91.8392',
      type: 'hill',
      rank: 19,
  },
  {
      city: 'Sitakunda, Chittagong',
      spotName: 'Banshbaria Beach',
      latitude: '22.1724',
      longitude: '91.7699',
      type: 'beach',
      rank: 20,
  },
  {
      city: 'Mongla, Khulna',
      spotName: 'Sundarbans Mangrove Forest',
      latitude: '21.9497',
      longitude: '89.1833',
      type: 'forest',
      rank: 21,
  },
  {
      city: 'Cox\'s Bazar Sadar, Chittagong',
      spotName: 'Cox\'s Bazar Beach',
      latitude: '21.4272',
      longitude: '92.0058',
      type: 'beach',
      rank: 22,
  },
  {
      city: 'Srimangal, Sylhet',
      spotName: 'Srimangal Tea Gardens',
      latitude: '24.3065',
      longitude: '91.7296',
      type: 'tea gardens',
      rank: 23,
  },
  {
      city: 'Kalapara, Barisal',
      spotName: 'Kuakata Beach',
      latitude: '21.8167',
      longitude: '90.1167',
      type: 'beach',
      rank: 24,
  },
  {
      city: 'Rangamati Sadar, Chittagong',
      spotName: 'Rangamati Hill Tracts',
      latitude: '22.7333',
      longitude: '92.3000',
      type: 'mountain',
      rank: 25,
  },
  {
      city: 'Baghaichhari, Chittagong',
      spotName: 'Sajek Valley',
      latitude: '23.3804',
      longitude: '92.2931',
      type: 'valley',
      rank: 26,
  },
  {
      city: 'Teknaf, Chittagong',
      spotName: "Saint Martin's Island",
      latitude: '20.6348',
      longitude: '92.4942',
      type: 'island',
      rank: 27,
  },
  {
      city: 'Badalgachhi, Rajshahi',
      spotName: 'Paharpur Buddhist Vihara',
      latitude: '25.0181',
      longitude: '88.9739',
      type: 'buddhist vihara',
      rank: 28,
  },
  {
      city: 'Lalbagh, Dhaka',
      spotName: 'Lalbagh Fort',
      latitude: '23.7075',
      longitude: '90.3995',
      type: 'fort',
      rank: 29,
  },
  {
      city: 'Shibganj, Rajshahi',
      spotName: 'Mahasthangarh Archaeological Site',
      latitude: '24.7876',
      longitude: '89.6333',
      type: 'archaeological site',
      rank: 30,
  },
  {
      city: 'Sonargaon, Dhaka',
      spotName: 'Sonargaon Folk Art and Craft Museum',
      latitude: '23.6097',
      longitude: '90.6161',
      type: 'museum',
      rank: 31,
  },
  {
      city: 'Bagerhat Sadar, Khulna',
      spotName: 'Sixty Dome Mosque',
      latitude: '22.8619',
      longitude: '89.7742',
      type: 'mosque',
      rank: 32,
  },
  {
      city: 'Bagerhat Sadar, Khulna',
      spotName: 'Bagerhat Mosque City',
      latitude: '22.6601',
      longitude: '89.7915',
      type: 'mosque city',
      rank: 33,
  },
  {
      city: 'Puthia, Rajshahi',
      spotName: 'Puthia Temple Complex',
      latitude: '24.1975',
      longitude: '88.9614',
      type: 'temple complex',
      rank: 34,
  },
  {
      city: 'Kotwali, Dhaka',
      spotName: 'Ahsan Manzil',
      latitude: '23.7085',
      longitude: '90.4076',
      type: 'manzil',
      rank: 35,
  },
  {
      city: 'Savar, Dhaka',
      spotName: "National Martyrs' Memorial",
      latitude: '23.7936',
      longitude: '90.3537',
      type: 'memorial',
      rank: 36,
  },
  {
      city: 'Badalgachhi, Rajshahi',
      spotName: 'Paharpur Buddhist Monastery',
      latitude: '25.0181',
      longitude: '88.9739',
      type: 'buddhist monastery',
      rank: 37,
  },
  {
      city: 'Gowainghat, Sylhet',
      spotName: 'Ratargul Swamp Forest',
      latitude: '24.3291',
      longitude: '91.8672',
      type: 'swamp forest',
      rank: 38,
  },
  {
      city: 'Kamolganj, Sylhet',
      spotName: 'Lawachara National Park',
      latitude: '24.4062',
      longitude: '91.7762',
      type: 'national park',
      rank: 39,
  }

    // ... (remaining objects with ranks)
  ] 